void TestPost()
{
    var approvalRequest = new ApprovalRequest();
	approvalRequest.desiredTermInMonths = 60;
	approvalRequest.originatorSalesRepId = "0035500000veq15AAA";
	approvalRequest.originatorId = "011411.0010";
	approvalRequest.subBrokerName = "";
	approvalRequest.splitTransaction = "NO";
	approvalRequest.comments = "Once upon a time, I needed a piece of equipment!";
	approvalRequest.creditRequested = 45000;
	approvalRequest.residual = "EFA";
	approvalRequest.programCode = "";
	var borrower = new borrower();
	borrower.legalCompanyName = "ARVI TRANSPORT COMPANY, INC.";
	borrower.dba = "";
	borrower.fedTaxId = "";
	borrower.billingStreet = "3 Endwood Circle";
	borrower.billingCity = "SUGARLOAF";
	borrower.billingStateCode = "PA";
	borrower.billingPostalCode = "18249";
	borrower.billingCountryCode = "US";
	//borrower.shippingStreet = "280 Ship Street";
	//borrower.shippingCity = "Minneapolis";
	//borrower.shippingStateCode = "MN";
	//borrower.shippingPostalCode = "91008";
	borrower.shippingStreet = "3 Endwood Circle";
	borrower.shippingCity = "SUGARLOAF";
	borrower.shippingStateCode = "PA";
	borrower.shippingPostalCode = "18249";
	borrower.phone = "5707885642";
	borrower.fax = "4443332000";
	borrower.businessEmail = "b@vv.com";
	borrower.businessStructure = "LLC";
	borrower.homeBusiness = "NO";
	borrower.website = "www.website.com";
	borrower.description = "488490 - Bridge, tunnel, and highway operations";
	borrower.verificationMethodComment = "verificationMethodComment";
	borrower.verificationMethod = "SECRETARY_OF_STATE";
	borrower.sic = "0111";
	borrower.businessStartDate = "2010-12-31" // (New DateTime(2010, 12, 31)).ToShortDateString();
	approvalRequest.borrower = borrower;
	var relationships = new List<Relationship>();
	var relationship = new Relationship();
	relationship.relationshipType = "Principal";
	var person = new person();
	person.firstName = "HARVEY";
	person.lastName = "TTESTFILE";
	person.ssn = "666663333";
	person.title = "CEO";
	person.percentageOwnership = 100;
	person.mailingStreet = "225 SEAHORSE RD";
	person.mailingCity = "CARSON";
	person.mailingStateCode = "CA";
	person.mailingPostalCode = "90745";
	person.mailingCountryCode = "US";
	person.homePhone = "5553322221";
	person.mobilePhone = "5553322124";
	person.email = "j@john.com";
	relationship.person = person;
	relationships.Add(relationship);
	approvalRequest.relationships = relationships;
	var equipmentList = new List<Equipment>();
	var equipment = new Equipment();
	equipment.equipmentCostPerUnit = 25000.0;
	equipment.equipmentQuantity = 1;
	equipment.description = "Awesome truck";
	equipment.typeOfTransaction = "VENDOR_SALE";
	equipment.condition = "NEW";
	equipment.equipmentType = "001.002";
	equipmentList.Add(equipment);
	approvalRequest.equipmentList = equipmentList;
	var json = JsonConvert.SerializeObject(approvalRequest);
	console.WriteLine(json);

}
